preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  org.jetbrains.kotlin.multiplatform:
    alias: kotlin-multiplatform
    version: 1.9.10
  org.jetbrains.compose:
    alias: jetbrains-compose
    version: 1.5.1
  com.android.application:
    alias: android-application
    version: 8.1.2
  com.android.library:
    alias: android-library
    version-ref: android-application

libraries:
  app.cash.paging:
    paging-common:
      version: 3.3.0-alpha02-0.4.0
    paging-compose-common:
      version-ref: <this>::paging-common
  androidx.activity:
    activity:
      version: 1.8.0
    activity-compose:
      version: 1.7.2
  androidx.core:
    core-ktx:
      version: 1.10.0
  androidx.appcompat:
    appcompat:
      version: 1.6.1
  com.google.android.material:
    material:
      version: 1.8.0
  androidx.test.ext:
    junit:
      version: 1.1.5
  androidx.test.espresso:
    espresso-core:
      version: 3.5.1
  junit:
    junit:
      version: 4.13.2